# Form implementation generated from reading ui file 'designer/speech_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import math
import typing
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget
from qtpy.QtGui import QCloseEvent

from package.ui.custom_button import CustomQPButton


class Ui_SpeechWindow(QWidget):
    def __init__(self, parent, window_key):
        super().__init__()

        self.parent = parent
        self.window_key = window_key

        self.setupUi(self)

    def setupUi(self, SpeechWindow):
        SpeechWindow.setObjectName("SpeechWindow")
        SpeechWindow.resize(190, 95)
        self.setFixedSize(190, 95)

        SpeechWindow.setWindowFlags(QtCore.Qt.WindowType.WindowStaysOnTopHint)

        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=SpeechWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 141, 70))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.main_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.main_layout.addItem(spacerItem)

        # Layout stop
        self.layout_stop = QtWidgets.QVBoxLayout()
        self.layout_stop.setObjectName("layout_stop")

        # Button stop
        # self.button_stop = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.button_stop = CustomQPButton(on_click=lambda: print("stop"))
        self.button_stop.setMinimumSize(QtCore.QSize(0, 48))
        self.button_stop.setStyleSheet("border:none; background-color: transparent;")
        self.button_stop.setText("")

        icon_stop = QtGui.QIcon()
        icon_stop.addPixmap(
            QtGui.QPixmap("./icons/stop.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.button_stop.setIcon(icon_stop)

        self.button_stop.setIconSize(QtCore.QSize(32, 32))
        self.button_stop.setObjectName("button_stop")

        self.layout_stop.addWidget(self.button_stop)

        # Label stop
        self.label_stop = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_stop.setObjectName("label_stop")
        # self.label_stop.setStyleSheet("align-text: center;")
        self.label_stop.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.layout_stop.addWidget(self.label_stop)

        self.main_layout.addLayout(self.layout_stop)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.main_layout.addItem(spacerItem1)

        # Layout download
        self.layout_download = QtWidgets.QVBoxLayout()
        self.layout_download.setObjectName("layout_download")

        # Button download
        # self.button_download = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.button_download = CustomQPButton(on_click=lambda: print("download"))
        self.button_download.setMinimumSize(QtCore.QSize(0, 48))
        self.button_download.setStyleSheet(
            "border:none; background-color: transparent;"
        )
        self.button_download.setText("")

        icon_download = QtGui.QIcon()
        icon_download.addPixmap(
            QtGui.QPixmap("./icons/download.svg"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.button_download.setIcon(icon_download)

        self.button_download.setIconSize(QtCore.QSize(24, 24))
        self.button_download.setObjectName("button_download")

        self.layout_download.addWidget(self.button_download)

        # Label download
        self.label_download = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_download.setObjectName("label_download")
        self.label_download.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)

        self.layout_download.addWidget(self.label_download)
        self.main_layout.addLayout(self.layout_download)

        self.retranslateUi(SpeechWindow)
        QtCore.QMetaObject.connectSlotsByName(SpeechWindow)

        self.topRightOffset(self)

    def retranslateUi(self, SpeechWindow):
        _translate = QtCore.QCoreApplication.translate
        SpeechWindow.setWindowTitle(_translate("SpeechWindow", "Respuesta"))
        self.label_stop.setText(_translate("SpeechWindow", "Parar"))
        self.label_download.setText(_translate("SpeechWindow", "Descargar"))

    def topRightOffset(self, obj):
        fg = obj.frameGeometry()
        screen = obj.screen()

        if screen is None:
            return

        available_geometry = screen.availableGeometry()

        x = math.floor((available_geometry.right() - fg.width()) / 2)
        # x = math.floor((available_geometry.right()) / 2) - fg.width()

        y = available_geometry.top()

        fg.moveCenter(available_geometry.center())

        obj.move(x, y)

    def closeEvent(self, a0: typing.Optional[QCloseEvent]) -> None:
        if not hasattr(self.parent, "windows") or not isinstance(self.parent, QWidget):
            return

        self.parent.handle_windows(self.window_key)

        return super().closeEvent(a0)
